server:
  port: 8080
  connection-timeout: 700000
feign:
  hystrix:
    enabled: true
hystrix:
  threadpool:
    default:
      coreSize: 1
      maxQueueSize: -1
  command:
    default:
      execution:
        isolation:
          strategy: Thread
          thread:
            timeoutInMilliseconds: 4000